INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('customer_id', 'auto', '79', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('store_id', 'auto', '0', {_ID}),
('language_id', 'auto', '0', {_ID}),
('firstname', 'auto', 'Jeffrey', {_ID}),
('lastname', 'auto', 'Zeldman', {_ID}),
('email', 'auto', 'user@oc.local', {_ID}),
('telephone', 'auto', '123456789', {_ID}),
('fax', 'auto', '987654321', {_ID}),
('wishlist', 'auto', '', {_ID}),
('newsletter', 'auto', 'No', {_ID}),
('address_id', 'auto', '0', {_ID}),
('custom_field', 'auto', 'a:1:{i:2;s:0:"";}', {_ID}),
('ip', 'auto', '', {_ID}),
('status', 'auto', '1', {_ID}),
('approved', 'auto', '1', {_ID}),
('safe', 'auto', '1', {_ID}),
('token', 'auto', '', {_ID}),
('date_added', 'auto', '2015-04-23 14:42:10', {_ID}),
('account_login', 'auto', 'http://oc.local/admin/index.php?route=account/login&amp;email=user@oc.local', {_ID}),
('account_login_tracking', 'auto', 'http://oc.local/admin/index.php?route=account/login&amp;email=user@oc.local', {_ID}),
('customer_group', 'auto', 'Default', {_ID});