INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('order_id', 'auto', '10', {_ID}),
('invoice_no', 'auto', '0', {_ID}),
('invoice_prefix', 'auto', 'INV-2000-00', {_ID}),
('customer_id', 'auto', '78', {_ID}),
('customer', 'auto', 'Jeffrey Zeldman', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('firstname', 'auto', 'Jeffrey', {_ID}),
('lastname', 'auto', 'Zeldman', {_ID}),
('email', 'auto', 'user@oc.local', {_ID}),
('telephone', 'auto', '123456789', {_ID}),
('fax', 'auto', '987654321', {_ID}),
('custom_field.2', 'auto', 'FSOMAY', {_ID}),
('payment_firstname', 'auto', 'Jeffrey', {_ID}),
('payment_lastname', 'auto', 'Zeldman', {_ID}),
('payment_company', 'auto', 'Opencart-templates', {_ID}),
('payment_address_1', 'auto', '1 Long lane', {_ID}),
('payment_address_2', 'auto', 'Village', {_ID}),
('payment_postcode', 'auto', 'LS6', {_ID}),
('payment_city', 'auto', 'Leeds', {_ID}),
('payment_zone_id', 'auto', '3608', {_ID}),
('payment_zone', 'auto', 'West Yorkshire', {_ID}),
('payment_zone_code', 'auto', 'YSW', {_ID}),
('payment_country_id', 'auto', '222', {_ID}),
('payment_country', 'auto', 'United Kingdom', {_ID}),
('payment_iso_code_2', 'auto', 'GB', {_ID}),
('payment_iso_code_3', 'auto', 'GBR', {_ID}),
('payment_address_format', 'auto', '', {_ID}),
('payment_custom_field.3', 'auto', '3', {_ID}),
('payment_method', 'auto', 'Bank Transfer', {_ID}),
('payment_code', 'auto', 'bank_transfer', {_ID}),
('shipping_firstname', 'auto', 'Jeffrey', {_ID}),
('shipping_lastname', 'auto', 'Zeldman', {_ID}),
('shipping_company', 'auto', 'Opencart-templates', {_ID}),
('shipping_address_1', 'auto', '1 Long lane', {_ID}),
('shipping_address_2', 'auto', 'Village', {_ID}),
('shipping_postcode', 'auto', 'LS6', {_ID}),
('shipping_city', 'auto', 'Leeds', {_ID}),
('shipping_zone_id', 'auto', '3608', {_ID}),
('shipping_zone', 'auto', 'West Yorkshire', {_ID}),
('shipping_zone_code', 'auto', 'YSW', {_ID}),
('shipping_country_id', 'auto', '222', {_ID}),
('shipping_country', 'auto', 'United Kingdom', {_ID}),
('shipping_iso_code_2', 'auto', 'GB', {_ID}),
('shipping_iso_code_3', 'auto', 'GBR', {_ID}),
('shipping_address_format', 'auto', '', {_ID}),
('shipping_custom_field.3', 'auto', '3', {_ID}),
('shipping_method', 'auto', 'Flat Shipping Rate', {_ID}),
('shipping_code', 'auto', 'flat.flat', {_ID}),
('comment', 'auto', 'Test\nMultiline\nComment\n', {_ID}),
('total', 'auto', '6549.2000', {_ID}),
('reward', 'auto', '4200', {_ID}),
('order_status_id', 'auto', '5', {_ID}),
('affiliate_id', 'auto', '0', {_ID}),
('affiliate_firstname', 'auto', '', {_ID}),
('affiliate_lastname', 'auto', '', {_ID}),
('commission', 'auto', '0.0000', {_ID}),
('language_id', 'auto', '1', {_ID}),
('language_code', 'auto', 'en', {_ID}),
('language_directory', 'auto', 'english', {_ID}),
('currency_id', 'auto', '2', {_ID}),
('currency_code', 'auto', 'USD', {_ID}),
('currency_value', 'auto', '1.00000000', {_ID}),
('ip', 'auto', '127.0.0.1', {_ID}),
('forwarded_ip', 'auto', '', {_ID}),
('user_agent', 'auto', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0', {_ID}),
('accept_language', 'auto', 'en-GB,en;q=0.5', {_ID}),
('date_added', 'auto', '2015-04-23 14:03:40', {_ID}),
('date_modified', 'auto', '2015-04-23 14:09:25', {_ID}),
('payment_address', 'auto', 'Jeffrey Zeldman<br />Opencart-templates<br />1 Long lane<br />Village<br />Leeds LS6<br />West Yorkshire<br />United Kingdom', {_ID}),
('shipping_address', 'auto', 'Jeffrey Zeldman<br />Opencart-templates<br />1 Long lane<br />Village<br />Leeds LS6<br />West Yorkshire<br />United Kingdom', {_ID});