INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('customer_customer_id', 'auto', '78', {_ID}),
('customer_customer_group_id', 'auto', '1', {_ID}),
('customer_store_id', 'auto', '0', {_ID}),
('customer_language_id', 'auto', '0', {_ID}),
('customer_firstname', 'auto', 'Jeffrey', {_ID}),
('customer_lastname', 'auto', 'Zeldman', {_ID}),
('customer_email', 'auto', 'user@oc.local', {_ID}),
('customer_telephone', 'auto', '123456789', {_ID}),
('customer_fax', 'auto', '987654321', {_ID}),
('customer_code', 'auto', '', {_ID}),
('customer_wishlist', 'auto', '', {_ID}),
('customer_newsletter', 'auto', '1', {_ID}),
('customer_address_id', 'auto', '67', {_ID}),
('customer_custom_field', 'auto', 'a:1:{i:2;s:6:"FSOMAY";}', {_ID}),
('customer_ip', 'auto', '127.0.0.1', {_ID}),
('customer_status', 'auto', '1', {_ID}),
('customer_approved', 'auto', '0', {_ID}),
('customer_safe', 'auto', '0', {_ID}),
('customer_token', 'auto', '', {_ID}),
('customer_date_added', 'auto', '2015-04-23 13:59:08', {_ID}),
('text_welcome', 'auto', 'Welcome and thank you for registering at Your Store!', {_ID}),
('account_login', 'auto', 'http://oc.local/index.php?route=account/login', {_ID}),
('account_login_tracking', 'auto', 'http://oc.local/index.php?route=account/login', {_ID});