INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('affiliate_affiliate_id', 'auto', '1', {_ID}),
('affiliate_firstname', 'auto', 'Jeffrey', {_ID}),
('affiliate_lastname', 'auto', 'Zeldman', {_ID}),
('affiliate_email', 'auto', 'user@oc.local', {_ID}),
('affiliate_telephone', 'auto', '123456789', {_ID}),
('affiliate_fax', 'auto', '987654321', {_ID}),
('affiliate_company', 'auto', 'Opencart-templates', {_ID}),
('affiliate_website', 'auto', 'http://www.opencart-templates.co.uk', {_ID}),
('affiliate_address_1', 'auto', '1 Long lane', {_ID}),
('affiliate_address_2', 'auto', 'Village', {_ID}),
('affiliate_city', 'auto', 'Leeds', {_ID}),
('affiliate_postcode', 'auto', 'LS6', {_ID}),
('affiliate_country_id', 'auto', '222', {_ID}),
('affiliate_zone_id', 'auto', '3608', {_ID}),
('affiliate_code', 'auto', '5538ee8a71f9c', {_ID}),
('affiliate_commission', 'auto', '5.00', {_ID}),
('affiliate_tax', 'auto', '999', {_ID}),
('affiliate_payment', 'auto', 'cheque', {_ID}),
('affiliate_cheque', 'auto', 'Jeffrey Zeldman', {_ID}),
('affiliate_paypal', 'auto', 'user@oc.local', {_ID}),
('affiliate_bank_name', 'auto', 'Jeffrey Zeldman', {_ID}),
('affiliate_bank_branch_number', 'auto', '', {_ID}),
('affiliate_bank_swift_code', 'auto', '', {_ID}),
('affiliate_bank_account_name', 'auto', 'Jeffrey Zeldman', {_ID}),
('affiliate_bank_account_number', 'auto', '', {_ID}),
('affiliate_ip', 'auto', '', {_ID}),
('affiliate_status', 'auto', '1', {_ID}),
('affiliate_approved', 'auto', '0', {_ID}),
('affiliate_date_added', 'auto', '2015-04-23 14:07:22', {_ID}),
('password', 'auto', 'ec5e97637f', {_ID}),
('account_login', 'auto', 'http://oc.local/index.php?route=affiliate/login', {_ID}),
('account_login_tracking', 'auto', 'http://oc.local/index.php?route=affiliate/login', {_ID});