INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('affiliate_id', 'auto', '1', {_ID}),
('firstname', 'auto', 'Jeffrey', {_ID}),
('lastname', 'auto', 'Zeldman', {_ID}),
('email', 'auto', 'user@oc.local', {_ID}),
('telephone', 'auto', '123456789', {_ID}),
('fax', 'auto', '987654321', {_ID}),
('company', 'auto', 'Opencart-templates', {_ID}),
('website', 'auto', 'http://www.opencart-templates.co.uk', {_ID}),
('address_1', 'auto', '1 Long lane', {_ID}),
('address_2', 'auto', 'Village', {_ID}),
('city', 'auto', 'Leeds', {_ID}),
('postcode', 'auto', 'LS6', {_ID}),
('country_id', 'auto', '222', {_ID}),
('zone_id', 'auto', '3608', {_ID}),
('commission', 'auto', '5.00', {_ID}),
('tax', 'auto', '999', {_ID}),
('payment', 'auto', 'cheque', {_ID}),
('cheque', 'auto', 'Jeffrey Zeldman', {_ID}),
('paypal', 'auto', 'user@oc.local', {_ID}),
('bank_name', 'auto', 'Jeffrey Zeldman', {_ID}),
('bank_branch_number', 'auto', '', {_ID}),
('bank_swift_code', 'auto', '', {_ID}),
('bank_account_name', 'auto', 'Jeffrey Zeldman', {_ID}),
('bank_account_number', 'auto', '', {_ID}),
('ip', 'auto', '', {_ID}),
('status', 'auto', '1', {_ID}),
('approved', 'auto', '0', {_ID}),
('date_added', 'auto', '2015-04-23 14:07:22', {_ID}),
('url_affiliate_login', 'auto', 'http://oc.local/index.php?route=affiliate/login', {_ID}),
('url_affiliate_login_tracking', 'auto', 'http://oc.local/index.php?route=affiliate/login', {_ID});