INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('customer_group_id', 'auto', '1', {_ID}),
('firstname', 'auto', 'Jeffrey', {_ID}),
('lastname', 'auto', 'Zeldman', {_ID}),
('email', 'auto', 'user@oc.local', {_ID}),
('telephone', 'auto', '123456789', {_ID}),
('fax', 'auto', '987654321', {_ID}),
('company', 'auto', 'Opencart-templates', {_ID}),
('address_1', 'auto', '1 Long lane', {_ID}),
('address_2', 'auto', 'Village', {_ID}),
('city', 'auto', 'Leeds', {_ID}),
('postcode', 'auto', 'LS6', {_ID}),
('country_id', 'auto', '222', {_ID}),
('zone_id', 'auto', '3608', {_ID}),
('password', 'auto', 'password', {_ID}),
('confirm', 'auto', 'password', {_ID}),
('newsletter', 'auto', 'Yes', {_ID}),
('agree', 'auto', '1', {_ID}),
('custom_field_address_3_name', 'auto', 'How long have you lived at this address?', {_ID}),
('custom_field_address_3_value', 'auto', '3', {_ID}),
('custom_field_account_2_name', 'auto', 'Promo Code', {_ID}),
('custom_field_account_2_value', 'auto', 'FSOMAY', {_ID}),
('account_login', 'auto', 'http://oc.local/index.php?route=account/login&amp;email=user@oc.local', {_ID}),
('account_login_tracking', 'auto', 'http://oc.local/index.php?route=account/login&amp;email=user@oc.local', {_ID}),
('customer_group', 'auto', 'Default', {_ID}),
('address', 'auto', 'Jeffrey Zeldman<br />Opencart-templates<br />1 Long lane<br />Village<br />Leeds LS6<br />West Yorkshire<br />United Kingdom', {_ID}),
('customer_text', 'auto', 'Your account has now been created and you can log in by using your email address and password by visiting our website or at the following URL:', {_ID}),
('language_id', 'auto', '1', {_ID}),
('customer_id', 'auto', '0', {_ID}),
('tracking', 'auto', 'utm_campaign=Your+Store&utm_medium=email&utm_source=account%2Fregister', {_ID}),
('subject', 'auto', 'Welcome Jeffrey and thank you for registering at Your Store!', {_ID});