INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('order_order_id', 'auto', '10', {_ID}),
('order_invoice_no', 'auto', '0', {_ID}),
('order_invoice_prefix', 'auto', 'INV-2013-00', {_ID}),
('order_customer_id', 'auto', '78', {_ID}),
('order_customer_group_id', 'auto', '1', {_ID}),
('order_affiliate_id', 'auto', '0', {_ID}),
('order_weight', 'auto', '0.00000000', {_ID}),
('order_firstname', 'auto', 'Jeffrey', {_ID}),
('order_lastname', 'auto', 'Zeldman', {_ID}),
('order_email', 'auto', 'user@oc.local', {_ID}),
('order_telephone', 'auto', '123456789', {_ID}),
('order_fax', 'auto', '987654321', {_ID}),
('order_custom_field.2', 'auto', 'FSOMAY', {_ID}),
('order_payment_firstname', 'auto', 'Jeffrey', {_ID}),
('order_payment_lastname', 'auto', 'Zeldman', {_ID}),
('order_payment_company', 'auto', 'Opencart-templates', {_ID}),
('order_payment_address_1', 'auto', '1 Long lane', {_ID}),
('order_payment_address_2', 'auto', 'Village', {_ID}),
('order_payment_postcode', 'auto', 'LS6', {_ID}),
('order_payment_city', 'auto', 'Leeds', {_ID}),
('order_payment_zone_id', 'auto', '3608', {_ID}),
('order_payment_zone', 'auto', 'West Yorkshire', {_ID}),
('order_payment_zone_code', 'auto', 'YSW', {_ID}),
('order_payment_country_id', 'auto', '222', {_ID}),
('order_payment_country', 'auto', 'United Kingdom', {_ID}),
('order_payment_iso_code_2', 'auto', 'GB', {_ID}),
('order_payment_iso_code_3', 'auto', 'GBR', {_ID}),
('order_payment_address_format', 'auto', '', {_ID}),
('order_payment_custom_field.3', 'auto', '3', {_ID}),
('order_payment_method', 'auto', 'Bank Transfer', {_ID}),
('order_payment_code', 'auto', 'bank_transfer', {_ID}),
('order_shipping_firstname', 'auto', 'Jeffrey', {_ID}),
('order_shipping_lastname', 'auto', 'Zeldman', {_ID}),
('order_shipping_company', 'auto', 'Opencart-templates', {_ID}),
('order_shipping_address_1', 'auto', '1 Long lane', {_ID}),
('order_shipping_address_2', 'auto', 'Village', {_ID}),
('order_shipping_postcode', 'auto', 'LS6', {_ID}),
('order_shipping_city', 'auto', 'Leeds', {_ID}),
('order_shipping_zone_id', 'auto', '3608', {_ID}),
('order_shipping_zone', 'auto', 'West Yorkshire', {_ID}),
('order_shipping_zone_code', 'auto', 'YSW', {_ID}),
('order_shipping_country_id', 'auto', '222', {_ID}),
('order_shipping_country', 'auto', 'United Kingdom', {_ID}),
('order_shipping_iso_code_2', 'auto', 'GB', {_ID}),
('order_shipping_iso_code_3', 'auto', 'GBR', {_ID}),
('order_shipping_address_format', 'auto', '', {_ID}),
('order_shipping_custom_field.3', 'auto', '3', {_ID}),
('order_shipping_method', 'auto', 'Flat Shipping Rate', {_ID}),
('order_shipping_code', 'auto', 'flat.flat', {_ID}),
('order_comment', 'auto', 'Test\nMultiline\nComment\n', {_ID}),
('order_total', 'auto', '6549.2000', {_ID}),
('order_order_status_id', 'auto', '1', {_ID}),
('order_order_status', 'auto', 'Pending', {_ID}),
('order_commission', 'auto', '0.0000', {_ID}),
('order_language_id', 'auto', '1', {_ID}),
('order_language_code', 'auto', 'en', {_ID}),
('order_language_directory', 'auto', 'english', {_ID}),
('order_currency_id', 'auto', '2', {_ID}),
('order_currency_code', 'auto', 'USD', {_ID}),
('order_currency_value', 'auto', '1.00000000', {_ID}),
('order_ip', 'auto', '127.0.0.1', {_ID}),
('order_forwarded_ip', 'auto', '', {_ID}),
('order_user_agent', 'auto', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0', {_ID}),
('order_accept_language', 'auto', 'en-GB,en;q=0.5', {_ID}),
('order_date_modified', 'auto', '2015-04-23 14:03:43', {_ID}),
('order_date_added', 'auto', '2015-04-23 14:03:40', {_ID}),
('order_date', 'auto', '23/04/2015', {_ID}),
('return_id', 'auto', '2', {_ID}),
('order_id', 'auto', '10', {_ID}),
('firstname', 'auto', 'Jeffrey', {_ID}),
('lastname', 'auto', 'Zeldman', {_ID}),
('email', 'auto', 'user@oc.local', {_ID}),
('telephone', 'auto', '123456789', {_ID}),
('product', 'auto', 'iPod Touch', {_ID}),
('model', 'auto', 'Product 5', {_ID}),
('quantity', 'auto', '1', {_ID}),
('opened', 'auto', 'No', {_ID}),
('reason', 'auto', 'Faulty, please supply details', {_ID}),
('action', 'auto', '', {_ID}),
('status', 'auto', 'Awaiting Products', {_ID}),
('comment', 'auto', 'Test <br />\r\nMultiline<br />\r\nComment', {_ID}),
('date_ordered', 'auto', '2015-04-23', {_ID}),
('date_added', 'auto', '2015-04-23 14:06:33', {_ID}),
('date_modified', 'auto', '2015-04-23 14:06:33', {_ID}),
('return_date', 'auto', '23/04/2015', {_ID}),
('return_link', 'auto', 'http://oc.local/admin/index.php?route=sale/return/info&return_id=2', {_ID});