INSERT INTO `oc_emailtemplate_shortcode` (`emailtemplate_shortcode_code`, `emailtemplate_shortcode_type`, `emailtemplate_shortcode_example`, `emailtemplate_id`) VALUES
('customer_group.customer_group_id', 'auto', '1', {_ID}),
('customer_group.approval', 'auto', '0', {_ID}),
('customer_group.sort_order', 'auto', '1', {_ID}),
('customer_group.language_id', 'auto', '1', {_ID}),
('customer_group.name', 'auto', 'Default', {_ID}),
('customer_group.description', 'auto', 'test', {_ID}),
('order_id', 'auto', '10', {_ID}),
('invoice_no', 'auto', '0', {_ID}),
('invoice_prefix', 'auto', 'INV-2013-00', {_ID}),
('customer_id', 'auto', '78', {_ID}),
('customer_group_id', 'auto', '1', {_ID}),
('affiliate_id', 'auto', '0', {_ID}),
('weight', 'auto', '0.00000000', {_ID}),
('firstname', 'auto', 'Jeffrey', {_ID}),
('lastname', 'auto', 'Zeldman', {_ID}),
('email', 'auto', 'user@oc.local', {_ID}),
('telephone', 'auto', '123456789', {_ID}),
('fax', 'auto', '987654321', {_ID}),
('custom_field.2', 'auto', 'FSOMAY', {_ID}),
('payment_firstname', 'auto', 'Jeffrey', {_ID}),
('payment_lastname', 'auto', 'Zeldman', {_ID}),
('payment_company', 'auto', 'Opencart-templates', {_ID}),
('payment_address_1', 'auto', '1 Long lane', {_ID}),
('payment_address_2', 'auto', 'Village', {_ID}),
('payment_postcode', 'auto', 'LS6', {_ID}),
('payment_city', 'auto', 'Leeds', {_ID}),
('payment_zone_id', 'auto', '3608', {_ID}),
('payment_zone', 'auto', 'West Yorkshire', {_ID}),
('payment_zone_code', 'auto', 'YSW', {_ID}),
('payment_country_id', 'auto', '222', {_ID}),
('payment_country', 'auto', 'United Kingdom', {_ID}),
('payment_iso_code_2', 'auto', 'GB', {_ID}),
('payment_iso_code_3', 'auto', 'GBR', {_ID}),
('payment_address_format', 'auto', '', {_ID}),
('payment_custom_field.3', 'auto', '3', {_ID}),
('payment_method', 'auto', 'Bank Transfer', {_ID}),
('payment_code', 'auto', 'bank_transfer', {_ID}),
('shipping_firstname', 'auto', 'Jeffrey', {_ID}),
('shipping_lastname', 'auto', 'Zeldman', {_ID}),
('shipping_company', 'auto', 'Opencart-templates', {_ID}),
('shipping_address_1', 'auto', '1 Long lane', {_ID}),
('shipping_address_2', 'auto', 'Village', {_ID}),
('shipping_postcode', 'auto', 'LS6', {_ID}),
('shipping_city', 'auto', 'Leeds', {_ID}),
('shipping_zone_id', 'auto', '3608', {_ID}),
('shipping_zone', 'auto', 'West Yorkshire', {_ID}),
('shipping_zone_code', 'auto', 'YSW', {_ID}),
('shipping_country_id', 'auto', '222', {_ID}),
('shipping_country', 'auto', 'United Kingdom', {_ID}),
('shipping_iso_code_2', 'auto', 'GB', {_ID}),
('shipping_iso_code_3', 'auto', 'GBR', {_ID}),
('shipping_address_format', 'auto', '', {_ID}),
('shipping_custom_field.3', 'auto', '3', {_ID}),
('shipping_method', 'auto', 'Flat Shipping Rate', {_ID}),
('shipping_code', 'auto', 'flat.flat', {_ID}),
('comment', 'auto', 'Bank Transfer Instructions\n\nTransfer total amount to: ...\r\n\r\nYour order will not be processed until payment has been received\n\nYour order will not ship until we receive payment.', {_ID}),
('total', 'auto', '6549.2000', {_ID}),
('order_status_id', 'auto', '0', {_ID}),
('order_status', 'auto', 'Pending', {_ID}),
('commission', 'auto', '0.0000', {_ID}),
('language_id', 'auto', '1', {_ID}),
('language_code', 'auto', 'en', {_ID}),
('language_directory', 'auto', 'english', {_ID}),
('currency_id', 'auto', '2', {_ID}),
('currency_code', 'auto', 'USD', {_ID}),
('currency_value', 'auto', '1.00000000', {_ID}),
('ip', 'auto', '127.0.0.1', {_ID}),
('forwarded_ip', 'auto', '', {_ID}),
('user_agent', 'auto', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0', {_ID}),
('accept_language', 'auto', 'en-GB,en;q=0.5', {_ID}),
('date_modified', 'auto', '2015-04-23 14:03:40', {_ID}),
('date_added', 'auto', '23/04/2015', {_ID}),
('new_order_status', 'auto', 'Pending', {_ID}),
('text_greeting', 'auto', 'Thank you for your interest in Your Store products. Your order has been received and will be processed once payment has been confirmed.', {_ID}),
('text_link', 'auto', 'To view your order click on the link below:', {_ID}),
('text_download', 'auto', 'Once your payment has been confirmed you can click on the link below to access your downloadable products:', {_ID}),
('text_order_detail', 'auto', 'Order Details', {_ID}),
('text_instruction', 'auto', 'Instructions', {_ID}),
('text_order_id', 'auto', 'Order ID:', {_ID}),
('text_date_added', 'auto', 'Date Added:', {_ID}),
('text_payment_method', 'auto', 'Payment Method:', {_ID}),
('text_shipping_method', 'auto', 'Shipping Method:', {_ID}),
('text_email', 'auto', 'E-mail:', {_ID}),
('text_telephone', 'auto', 'Telephone:', {_ID}),
('text_ip', 'auto', 'IP Address:', {_ID}),
('text_order_status', 'auto', 'Order Status:', {_ID}),
('text_payment_address', 'auto', 'Payment Address', {_ID}),
('text_shipping_address', 'auto', 'Shipping Address', {_ID}),
('text_product', 'auto', 'Product', {_ID}),
('text_model', 'auto', 'Model', {_ID}),
('text_quantity', 'auto', 'Quantity', {_ID}),
('text_price', 'auto', 'Price', {_ID}),
('text_total', 'auto', 'Total', {_ID}),
('text_footer', 'auto', 'Please reply to this e-mail if you have any questions.', {_ID}),
('logo', 'auto', 'http://oc.local/image/catalog/logo.png', {_ID}),
('link', 'auto', 'http://oc.local/index.php?route=account/order/info&order_id=10', {_ID}),
('download', 'auto', '', {_ID}),
('payment_address', 'auto', 'Jeffrey Zeldman<br />Opencart-templates<br />1 Long lane<br />Village<br />Leeds LS6<br />West Yorkshire<br />United Kingdom', {_ID}),
('shipping_address', 'auto', 'Jeffrey Zeldman<br />Opencart-templates<br />1 Long lane<br />Village<br />Leeds LS6<br />West Yorkshire<br />United Kingdom', {_ID}),
('link_tracking', 'auto', 'http://oc.local/index.php?route=account/order/info&order_id=10', {_ID}),
('order_total', 'auto', '£6,549.50', {_ID}),
('order_comment', 'auto', 'Test<br />\nMultiline<br />\nComment<br />\n', {_ID}),
('instruction', 'auto', 'Bank Transfer Instructions<br />\n<br />\nTransfer total amount to: ...<br />\r\n<br />\r\nYour order will not be processed until payment has been received<br />\n<br />\nYour order will not ship until we receive payment.', {_ID});