<?php
// Heading
$_['heading_title']       = 'Product Returns';

// Text
$_['text_success']        = 'Success: You have modified returns!';
$_['text_list']           = 'Product Return List';
$_['text_add']            = 'Add Product Return';
$_['text_edit']           = 'Edit Product Return';
$_['text_opened']         = 'Opened';
$_['text_unopened']       = 'Unopened';
$_['text_order']          = 'Order Information';
$_['text_product']        = 'Product Information &amp; Reason for Return';
$_['text_history']        = 'Add Return History';

// Column
$_['column_return_id']     = 'Return ID';
$_['column_order_id']      = 'Order ID';
$_['column_customer']      = 'Customer';
$_['column_product']       = 'Product';
$_['column_model']         = 'Model';
$_['column_status']        = 'Status';
$_['column_date_added']    = 'Date Added';
$_['column_date_modified'] = 'Date Modified';
$_['column_comment']       = 'Comment';
$_['column_notify']        = 'Customer Notified';
$_['column_action']        = 'Action';

// Entry
$_['entry_customer']      = 'Customer';
$_['entry_order_id']      = 'Order ID';
$_['entry_date_ordered']  = 'Order Date';
$_['entry_firstname']     = 'First Name';
$_['entry_lastname']      = 'Last Name';
$_['entry_email']         = 'E-Mail';
$_['entry_telephone']     = 'Telephone';
$_['entry_product']       = 'Product';
$_['entry_model']         = 'Model';
$_['entry_quantity']      = 'Quantity';
$_['entry_price']         = 'Returned Price';
$_['entry_orignal_price'] = 'Ordered Price';
$_['entry_opened']        = 'Opened';
$_['entry_comment']       = 'Comment';
$_['entry_return_reason'] = 'Return Reason';
$_['entry_return_action'] = 'Return Action';
$_['entry_return_status'] = 'Return Status';
$_['entry_notify']        = 'Notify Customer';
$_['entry_return_id']     = 'Return ID';
$_['entry_date_added']    = 'Date Added';
$_['entry_date_modified'] = 'Date Modified';

// Help
$_['help_product']        = '(Autocomplete)';

// Error
$_['error_warning']       = 'Warning: Please check the form carefully for errors!';
$_['error_permission']    = 'Warning: You do not have permission to modify returns!';
$_['error_order_id']      = 'Order ID required!';
$_['error_firstname']     = 'First Name must be between 1 and 32 characters!';
$_['error_lastname']      = 'Last Name must be between 1 and 32 characters!';
$_['error_email']         = 'E-Mail Address does not appear to be valid!';
$_['error_telephone']     = 'Telephone must be between 3 and 32 characters!';
$_['error_product']       = 'Product Name must be greater than 3 and less than 255 characters!';
$_['error_model']         = 'Product Model must be greater than 3 and less than 64 characters!';


$_['heading_title_details']   = 'Return Details ';
$_['heading_title_setting']   = 'Return Setting ';

// Text
$_['text_success']    	 	  = 'Success: You have modified and updated Return !';
$_['text_rma']              = 'Return';
$_['text_success_setting']    = 'Success: You have updated Return Settings!';
$_['text_list']      		  = 'Return List Generated By Customers';
$_['button_clrfilter'] 		  = 'Clear Filter';
$_['button_invoice'] 		  = 'Print Invoice';
$_['button_alert'] 		  	  = 'Alert View';
$_['button_table'] 		  	  = 'Table View';
$_['text_no_recored']      	  = 'No Records Found !!';
$_['text_form'] 		  	  = 'View Return Id ';
$_['text_shipping_label'] 	  = 'Shipping Label';
$_['entry_message_by'] 	  = 'Message By';
$_['text_shipping_label'] 	  = 'Shipping Label';
$_['text_rma_not_found'] 	  = 'Return not found.';
// $_['text_shipping_info'] 	  = 'An identification label affixed to a container which specifies contents of the shipping container. If the merchandise is subject to any inspections such as an FDA inspection, the shipping label must contain that inspection information as well. A shipping label used by a mail carrier lists the originating and destination addresses. <a href="http://www.businessdictionary.com/definition/shipping-label.html#ixzz3K42zCxi9" target="_blank">Read more</a> <br/> <b>You can upload and send label from here and can select from previously added label(s).</b>';
$_['text_shipping_info'] 	  = '';
$_['text_generate_rma'] 	  = 'Add Customer Return';
$_['entry_name'] 	  = 'Customer Name';

//user
$_['text_invoice']    			  		 	  = 'Return';
$_['text_rmaid']    			  		 	  = 'Return Id ';
$_['text_images']    			  		 	  = 'Images';
$_['text_customer_tracking']    			  = 'Tracking/Consignment No. : ';
$_['text_no_option']    			  		  = 'No Status Available';
$_['text_quantity']    			  			  = 'Quantity Returned to Store';
$_['text_canceled']    			  		 	  = 'Canceled';
$_['text_solved']    			  			  = 'Solved';
$_['text_download']    			  			  = 'Attachment';
$_['text_to']                          ='To';
$_['text_ship_to']                          ='Ship To';
$_['title']                          ='Return';
$_['text_addinfo']                          ='Additional Information';
$_['text_rma_status']                    ='Return Status';
$_['text_admin_status']                  ='Admin Status';
$_['text_reason']                        ='Reason';
$_['wk_viewrma_msg']    			  		  = 'Save';
$_['wk_viewrma_shipping_label']    			  = 'Send Label';

$_['text_admin_return_text']    			  = 'Product has been restocked at store.';
$_['text_admin_return_info']    			  = 'Return Quantity will work on price + tax + rewards .';
$_['text_admin_return']    			  	  = 'Return Quantity';
$_['text_admin_model']    			  	  = 'Model Number';
$_['text_admin_qty_shipped']    			= 'Qty Shipped';
$_['text_admin_unit_price']    			= 'Unit Price';
$_['text_admin_total_price']			= 'Return Total';
$_['text_admin_shipped_total']			= 'Shipped Total';
$_['text_admin_images']    			  	  = 'Return Images';
$_['text_admin_id']    			  		  = 'Status';
$_['text_admin_product']    			  	  = 'Products';
$_['text_admin_cid']    			  		  = 'Customer Id';
$_['text_admin_cname']    			 	  = 'Customer Name ';
$_['text_admin_oid']    			  		  = 'Order Id ';
$_['text_admin_reason']    		  		  = 'Reason ';
$_['text_admin_date']    			  		  = ' Date';
$_['text_admin_rmastatus']    	  		  = 'Return Status ';
$_['text_admin_adminstatus']   	  		  = 'Select Return Status';
$_['text_admin_authno']   	  		 	  = 'Consignment Number ';
$_['text_admin_add_info']  	  		  	  = 'Additional Information ';
$_['text_admin_msg']  			  		  = 'Message';
$_['text_admin_basic']  			  		  = 'Return Details ';
$_['text_admin_msg_tab']		  	  		  = 'Conversation';
$_['text_admin_policy']		  	  		  = 'Enter Return Policy Description';

$_['text_generate_voucher']       = 'Click here to generate voucher.';
$_['text_amount']                 = 'Enter the amount.';
$_['text_voucher']                = 'Voucher';
$_['text_send_voucher']           = 'Send vocher to Customer';
$_['text_disable_voucher']        = 'Disable Customer Voucher';
$_['text_enable_voucher']         = 'Enable Customer Voucher';
$_['text_tab_payment']            = 'Store Payment';

$_['text_label_image']	  	  	  = 'Image';
$_['text_label_name']	  	  	  = 'Name';
$_['text_status'] 				  = 'Return status';
$_['text_disabled'] 			  = 'Disabled';
$_['text_enabled'] 				  = 'Enabled ';
// Entry

$_['button_back']    	          = 'Back';
$_['button_save']    	          = 'Save';
$_['button_cancel']    	          = 'Cancel';
$_['button_delete']    	          = 'Delete';
// Error
$_['error_label']  	 		     = 'Warning: Please select or upload valid label!!';

$_['entry_description']      = 'Description';
$_['entry_amount']           = 'Amount';
$_['text_loading']           = 'Loading';
$_['button_transaction_add'] = 'Add Store credit';
$_['button_voucher_add']     = 'Add Voucher';
$_['default_text_desc']      = 'Return Credit for Return ID#%s';

$_['text_voucher_balance']    = 'Return Voucher Balance Given';
$_['text_canceled_customer'] 		 = 'Canceled by Customer';
$_['error_selected']              = 'Warning: Please select at least one option for deletion.';

$_['text_solved_customer']			 = 'Solved by Customer';

$_['entry_back_to_stock']			= 'Add Back to Stock';
$_['entry_apply_refund']			= 'Apply Refund to Order';