DROP TABLE IF EXISTS `oc_emailtemplate`;
CREATE TABLE IF NOT EXISTS `oc_emailtemplate`(
  `emailtemplate_id` int(11) NOT NULL AUTO_INCREMENT,
  `emailtemplate_key` varchar(64) NOT NULL,
  `emailtemplate_label` varchar(255) NOT NULL,
  `emailtemplate_type` enum('','customer','affiliate','order','admin') NOT NULL,
  `emailtemplate_template` varchar(255) NOT NULL,
  `emailtemplate_mail_to` varchar(255) NOT NULL,
  `emailtemplate_mail_cc` varchar(255) NOT NULL,
  `emailtemplate_mail_bcc` varchar(255) NOT NULL,
  `emailtemplate_mail_from` varchar(255) NOT NULL,
  `emailtemplate_mail_html` tinyint(1) NOT NULL DEFAULT '1',
  `emailtemplate_mail_plain_text` tinyint(1) NOT NULL DEFAULT '0',
  `emailtemplate_mail_sender` varchar(255) NOT NULL,
  `emailtemplate_mail_replyto` varchar(255) NOT NULL,
  `emailtemplate_mail_replyto_name` varchar(255) NOT NULL,
  `emailtemplate_mail_attachment` varchar(255) NOT NULL,
  `emailtemplate_attach_invoice` tinyint(1) NOT NULL DEFAULT '0',
  `emailtemplate_language_files` varchar(255) NOT NULL,
  `emailtemplate_wrapper_tpl` varchar(255) NOT NULL,
  `emailtemplate_tracking_campaign_source` varchar(255) NOT NULL,
  `emailtemplate_status` tinyint(1) NOT NULL DEFAULT '1',
  `emailtemplate_default` tinyint(1) NOT NULL DEFAULT '1',
  `emailtemplate_shortcodes` tinyint(1) NOT NULL DEFAULT '0',
  `emailtemplate_showcase` tinyint(1) NOT NULL DEFAULT '1',
  `emailtemplate_condition` TEXT NOT NULL,
  `emailtemplate_modified` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `emailtemplate_log` tinyint(1) NOT NULL,
  `emailtemplate_view_browser` tinyint(1) NOT NULL,
  `emailtemplate_config_id` int(11) NOT NULL,
  `store_id` int(11) NULL DEFAULT NULL,
  `customer_group_id` int(11) NULL DEFAULT NULL,
  `order_status_id` int(11) NULL DEFAULT NULL,
  `event_id` int(11) NULL DEFAULT NULL,
  PRIMARY KEY(`emailtemplate_id`),
  INDEX `KEY`(`emailtemplate_key`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO `oc_emailtemplate` (`emailtemplate_id`, `emailtemplate_key`, `emailtemplate_label`, `emailtemplate_type`, `emailtemplate_template`, `emailtemplate_mail_to`, `emailtemplate_mail_cc`, `emailtemplate_mail_bcc`, `emailtemplate_mail_from`, `emailtemplate_mail_html`, `emailtemplate_mail_plain_text`, `emailtemplate_mail_sender`, `emailtemplate_mail_replyto`, `emailtemplate_mail_replyto_name`, `emailtemplate_mail_attachment`, `emailtemplate_attach_invoice`, `emailtemplate_language_files`, `emailtemplate_wrapper_tpl`, `emailtemplate_tracking_campaign_source`, `emailtemplate_status`, `emailtemplate_default`, `emailtemplate_shortcodes`, `emailtemplate_showcase`, `emailtemplate_condition`, `emailtemplate_modified`, `emailtemplate_config_id`, `store_id`, `customer_group_id`, `order_status_id`) VALUES
(1, 'main', 'Default template', '', '', '', '', '', '', 1, 0, '', '', '', '', 0, '', '', '', 1, 1, 1, 1, '', '2015-01-01 00:00:00', 0, NULL, 0, 0);

DROP TABLE IF EXISTS `oc_emailtemplate_config`;
CREATE TABLE IF NOT EXISTS `oc_emailtemplate_config`(
  `emailtemplate_config_id` int(11) NOT NULL AUTO_INCREMENT,
  `emailtemplate_config_name` varchar(64) NOT NULL,
  `emailtemplate_config_email_width` smallint(6) NOT NULL,
  `emailtemplate_config_email_responsive` tinyint(1) NOT NULL,
  `emailtemplate_config_page_bg_color` varchar(32) NOT NULL,
  `emailtemplate_config_body_bg_image` varchar(255) NOT NULL,
  `emailtemplate_config_body_bg_image_repeat` varchar(32) NOT NULL,
  `emailtemplate_config_body_bg_image_position` varchar(32) NOT NULL,
  `emailtemplate_config_body_bg_color` varchar(32) NOT NULL,
  `emailtemplate_config_body_font_color` varchar(32) NOT NULL,
  `emailtemplate_config_body_link_color` varchar(32) NOT NULL,
  `emailtemplate_config_body_heading_color` varchar(32) NOT NULL,
  `emailtemplate_config_body_section_bg_color` varchar(32) NOT NULL,
  `emailtemplate_config_page_footer_text` text NOT NULL,
  `emailtemplate_config_footer_text` text NOT NULL,
  `emailtemplate_config_footer_align` varchar(32) NOT NULL,
  `emailtemplate_config_footer_valign` varchar(32) NOT NULL,
  `emailtemplate_config_footer_font_color` varchar(32) NOT NULL,
  `emailtemplate_config_footer_height` smallint(6) NOT NULL,
  `emailtemplate_config_footer_section_bg_color` varchar(32) NOT NULL,
  `emailtemplate_config_header_bg_color` varchar(32) NOT NULL,
  `emailtemplate_config_header_bg_image` varchar(255) NOT NULL,
  `emailtemplate_config_header_height` smallint(6) NOT NULL,
  `emailtemplate_config_header_border_color` varchar(32) NOT NULL,
  `emailtemplate_config_header_section_bg_color` varchar(32) NOT NULL,
  `emailtemplate_config_head_text` text NOT NULL,
  `emailtemplate_config_head_section_bg_color` varchar(32) NOT NULL,
  `emailtemplate_config_view_browser_text` text NOT NULL,
  `emailtemplate_config_logo` varchar(255) NOT NULL,
  `emailtemplate_config_logo_align` varchar(32) NOT NULL,
  `emailtemplate_config_logo_font_color` varchar(32) NOT NULL,
  `emailtemplate_config_logo_font_size` smallint(6) NOT NULL,
  `emailtemplate_config_logo_height` smallint(6) NOT NULL,
  `emailtemplate_config_logo_valign` varchar(32) NOT NULL,
  `emailtemplate_config_logo_width` smallint(6) NOT NULL,
  `emailtemplate_config_shadow_top` text NOT NULL,
  `emailtemplate_config_shadow_left` text NOT NULL,
  `emailtemplate_config_shadow_right` text NOT NULL,
  `emailtemplate_config_shadow_bottom` text NOT NULL,
  `emailtemplate_config_showcase` varchar(32) NOT NULL,
  `emailtemplate_config_showcase_limit` smallint(6) NOT NULL,
  `emailtemplate_config_showcase_selection` varchar(255) NOT NULL,
  `emailtemplate_config_showcase_title` varchar(255) NOT NULL,
  `emailtemplate_config_showcase_related` tinyint(1) NOT NULL,
  `emailtemplate_config_showcase_section_bg_color` varchar(32) NOT NULL,
  `emailtemplate_config_page_align` enum('left','right','center') NOT NULL DEFAULT 'center',
  `emailtemplate_config_text_align` varchar(32) NOT NULL,
  `emailtemplate_config_tracking` tinyint(1) NOT NULL DEFAULT '0',
  `emailtemplate_config_tracking_campaign_name` varchar(255) NOT NULL,
  `emailtemplate_config_tracking_campaign_term` varchar(255) NOT NULL,
  `emailtemplate_config_wrapper_tpl` varchar(255) NOT NULL,
  `emailtemplate_config_theme` varchar(64) NOT NULL,
  `emailtemplate_config_table_quantity` tinyint(1) NOT NULL,
  `emailtemplate_config_style` varchar(64) NOT NULL,
  `emailtemplate_config_version` varchar(64) NOT NULL,
  `emailtemplate_config_status` tinyint(1) NOT NULL DEFAULT '1',
  `emailtemplate_config_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `emailtemplate_config_log` tinyint(1) NOT NULL,
  `emailtemplate_config_log_read` tinyint(1) NOT NULL,
  `emailtemplate_config_view_browser_theme` tinyint(1) NOT NULL,
  `customer_group_id` int(11) NOT NULL,
  `store_id` int(11) NOT NULL,
  `language_id` int(11) NOT NULL,
  PRIMARY KEY(`emailtemplate_config_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO `oc_emailtemplate_config` SET 
`emailtemplate_config_id` = 1,
`emailtemplate_config_name` = '{$store_name}', 
`emailtemplate_config_email_width` = 580, 
`emailtemplate_config_email_responsive` = 1, 
`emailtemplate_config_page_bg_color` = '#FFFFFF', 
`emailtemplate_config_body_bg_color` = '#F9F9F9', 
`emailtemplate_config_body_font_color` = '#333333', 
`emailtemplate_config_body_link_color` = '#28B0EC',
`emailtemplate_config_body_heading_color` = '#079BDC',
`emailtemplate_config_footer_text` = '&lt;p stle=&quot;text-align:center; margin:0; padding:0;&quot;&gt;Powered&amp;nbsp;by&amp;nbsp;&lt;a href=&quot;http://www.opencart.com&quot; style=&quot;text-decoration:none; color:#28B0EC;&quot; target=&quot;_blank&quot;&gt;Opencart&lt;/a&gt;,&amp;nbsp;Designed&amp;nbsp;By&amp;nbsp;&lt;a href=&quot;http://www.opencart-templates.co.uk&quot; style=&quot;text-decoration:none; color:#28B0EC;&quot; target=&quot;_blank&quot;&gt;OpenCart-templates&lt;/a&gt;.&lt;/p&gt;\r\n', 
`emailtemplate_config_footer_align` = 'center', 
`emailtemplate_config_footer_valign` = 'middle', 
`emailtemplate_config_footer_font_color` = '#333333', 
`emailtemplate_config_footer_height` = 30,  
`emailtemplate_config_header_bg_color` = '#515151', 
`emailtemplate_config_header_bg_image` = 'catalog/emailtemplate/head-bg.jpg', 
`emailtemplate_config_header_height` = 130, 
`emailtemplate_config_view_browser_text` = '&lt;p&gt;If&amp;nbsp;you''re&amp;nbsp;having&amp;nbsp;difficulty&amp;nbsp;seeing&amp;nbsp;this&amp;nbsp;email,&amp;nbsp;&lt;a href=&quot;{$url}&quot; target=&quot;_blank&quot;&gt;click&amp;nbsp;here&lt;/a&gt;&lt;/p&gt;', 
`emailtemplate_config_logo` = '{$store_logo}', 
`emailtemplate_config_logo_align` = 'center', 
`emailtemplate_config_logo_font_color` = '#032c6f', 
`emailtemplate_config_logo_font_size` = 30, 
`emailtemplate_config_logo_height` = 50, 
`emailtemplate_config_logo_valign` = 'middle', 
`emailtemplate_config_logo_width` = 268, 
`emailtemplate_config_shadow_top` = 'YTo2OntzOjY6Imxlbmd0aCI7czowOiIiO3M6Nzoib3ZlcmxhcCI7czowOiIiO3M6NToic3RhcnQiO3M6MDoiIjtzOjM6ImVuZCI7czowOiIiO3M6ODoibGVmdF9pbWciO3M6MDoiIjtzOjk6InJpZ2h0X2ltZyI7czowOiIiO30=', 
`emailtemplate_config_shadow_left` = 'YTo0OntzOjY6Imxlbmd0aCI7czoxOiI5IjtzOjc6Im92ZXJsYXAiO3M6MToiOCI7czo1OiJzdGFydCI7czo3OiIjZjhmOGY4IjtzOjM6ImVuZCI7czo3OiIjZDRkNGQ0Ijt9', 
`emailtemplate_config_shadow_right` = 'YTo0OntzOjY6Imxlbmd0aCI7czoxOiI5IjtzOjc6Im92ZXJsYXAiO3M6MToiOCI7czo1OiJzdGFydCI7czo3OiIjZDRkNGQ0IjtzOjM6ImVuZCI7czo3OiIjZjhmOGY4Ijt9', 
`emailtemplate_config_shadow_bottom` = 'YTo2OntzOjY6Imxlbmd0aCI7czoxOiI5IjtzOjc6Im92ZXJsYXAiO3M6MToiOCI7czo1OiJzdGFydCI7czo3OiIjZDRkNGQ0IjtzOjM6ImVuZCI7czo3OiIjZjhmOGY4IjtzOjg6ImxlZnRfaW1nIjtzOjQyOiJjYXRhbG9nL2VtYWlsdGVtcGxhdGUvZ3JheS9ib3R0b21fbGVmdC5wbmciO3M6OToicmlnaHRfaW1nIjtzOjQzOiJjYXRhbG9nL2VtYWlsdGVtcGxhdGUvZ3JheS9ib3R0b21fcmlnaHQucG5nIjt9', 
`emailtemplate_config_showcase` = 'latest', 
`emailtemplate_config_showcase_limit` = 4, 
`emailtemplate_config_showcase_title` = 'You May Also Like', 
`emailtemplate_config_showcase_related` = 1, 
`emailtemplate_config_page_align` = 'center', 
`emailtemplate_config_text_align` = 'left', 
`emailtemplate_config_tracking` = 0,
`emailtemplate_config_tracking_campaign_name` = '{$store_name}', 
`emailtemplate_config_theme` = 'default', 
`emailtemplate_config_style` = 'page',
`emailtemplate_config_version` = '2.6.17.5', 
`emailtemplate_config_table_quantity` = 1, 
`emailtemplate_config_status` = 1, 
`emailtemplate_config_modified` = '2015-01-01 00:00:00', 
`emailtemplate_config_log` = 1, 
`emailtemplate_config_log_read` = 1,
`customer_group_id` = 0, 
`store_id` = 0, 
`language_id` = 0;

DROP TABLE IF EXISTS `oc_emailtemplate_description`;
CREATE TABLE IF NOT EXISTS `oc_emailtemplate_description`(
  `emailtemplate_id` int(11) NOT NULL,
  `language_id` int(11) NOT NULL,
  `emailtemplate_description_subject` varchar(120) NOT NULL,
  `emailtemplate_description_preview` varchar(255) NOT NULL,
  `emailtemplate_description_content1` longtext NOT NULL,
  `emailtemplate_description_content2` longtext NOT NULL,
  `emailtemplate_description_content3` longtext NOT NULL,
  `emailtemplate_description_comment` longtext NOT NULL,
  `emailtemplate_description_unsubscribe_text` varchar(255) NOT NULL,
  PRIMARY KEY(`emailtemplate_id`, `language_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO `oc_emailtemplate_description` (`emailtemplate_id`, `language_id`, `emailtemplate_description_subject`, `emailtemplate_description_preview`, `emailtemplate_description_content1`, `emailtemplate_description_content2`, `emailtemplate_description_content3`, `emailtemplate_description_comment`, `emailtemplate_description_unsubscribe_text`) VALUES
(1, 0, '', '', '', '', '', '', '');

DROP TABLE IF EXISTS `oc_emailtemplate_shortcode`;
CREATE TABLE IF NOT EXISTS `oc_emailtemplate_shortcode`(
  `emailtemplate_shortcode_id` int(11) NOT NULL AUTO_INCREMENT,
  `emailtemplate_shortcode_code` varchar(255) NOT NULL,
  `emailtemplate_shortcode_type` enum('language', 'auto', 'auto_serialize') NOT NULL DEFAULT 'language',
  `emailtemplate_shortcode_example` TEXT NOT NULL,
  `emailtemplate_id` int(11) NOT NULL,
  PRIMARY KEY(`emailtemplate_shortcode_id`),
  KEY `emailtemplate_id` (`emailtemplate_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

DROP TABLE IF EXISTS `oc_emailtemplate_logs`;
CREATE TABLE IF NOT EXISTS `oc_emailtemplate_logs` (
  `emailtemplate_log_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `emailtemplate_log_sent` datetime NULL DEFAULT NULL,
  `emailtemplate_log_read` datetime NULL DEFAULT NULL,
  `emailtemplate_log_read_last` datetime NULL DEFAULT NULL,
  `emailtemplate_log_type` enum('','SYSTEM','CONTACT') COLLATE utf8_general_ci NOT NULL,
  `emailtemplate_log_to` varchar(255) COLLATE utf8_general_ci NOT NULL,
  `emailtemplate_log_from` varchar(255) COLLATE utf8_general_ci NOT NULL,
  `emailtemplate_log_sender` varchar(255) COLLATE utf8_general_ci NOT NULL,
  `emailtemplate_log_subject` varchar(255) COLLATE utf8_general_ci NOT NULL,
  `emailtemplate_log_text` longtext COLLATE utf8_general_ci NOT NULL,
  `emailtemplate_log_content` longtext COLLATE utf8_general_ci NOT NULL,
  `emailtemplate_log_enc` varchar(255) COLLATE utf8_general_ci NOT NULL,
  `emailtemplate_id` int(11) NOT NULL,
  `customer_id` int(11) NOT NULL,
  `order_id` int(11) NOT NULL,
  `store_id` int(11) NOT NULL,
  PRIMARY KEY (`emailtemplate_log_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;