<?php
/**
 * Webkul Software.
 * @category  Webkul
 * @author    Webkul
 * @copyright Copyright (c) 2010-2016 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// Heading Goes here:
$_['heading_title']      	  = 'Return Status ';
$_['heading_title_insert']    = 'New Status ';
$_['heading_title_update']    = 'Update Status';

// Text
$_['text_module']     	 	  = 'Modules';
$_['text_success']    	 	  = 'Success: You have been successfully modified Return Status .';
$_['text_success_insert']     = 'Success: You have been successfully added New Return Status .';
$_['text_success_update']     = 'Success: You have been successfully updated Return Status .';

// Entry
$_['text_no_records']      		  = 'No Records Found !!';
$_['text_list']      		  	  = 'Status List';
$_['text_info']        		  	  = 'Please select Order status wisely, if you selected anyone before then please don\'t select again. ';
$_['text_disable']        		  = 'Disable';
$_['text_enable']      		  	  = 'Enable';
$_['entry_status']      		  = 'Status';
$_['entry_name']         	      = 'Name';
$_['entry_match_order']    	      = 'Match Order Status';
$_['entry_assign_to']    	      = 'Status';
$_['entry_customer']    	      = 'Customer';
$_['entry_admin']    	     	  = 'Admin';
$_['entry_order_status']     	  = 'Order Status';
$_['entry_color']         	      = 'Color';
$_['text_color']         	       =  'Not defined';
$_['button_clrfilter']    	      = 'Clear Filter';
$_['button_back']    	          = 'Back';
$_['button_save']    	          = 'Save';
$_['button_cancel']    	          = 'Cancel';
$_['button_delete']    	          = 'Delete';
$_['text_edit']    	          	  = 'Edit';
$_['text_form']     	 	  	  = 'Add Status';
$_['text_edit_form']   	 	  	  = 'Edit Status';

$_['entry_default']    	          = 'Status For Customer';
$_['entry_default_cancel']    	  = 'For Cancel';
$_['entry_default_solved']    	  = 'For Solve';
$_['entry_default_info']    	  = 'After select Solve or Cancel Return Option through Customer .';
$_['entry_default_admin']    	  = 'Default Admin Status';
$_['entry_defaultAdmin_info']     = 'After Return generated by Customer this will be Admin\'s default Status ';
// Error
$_['error_permission']  	 	  = 'Warning: You do not have permission to modify Product Return Return - Status !!';
$_['error_name']  	  	  	  	  = 'Warning: Name must have between 5 to 50 characters !!';
$_['error_select'] 	  	  	  	  = 'Warning: Please select Admin or Customer for this Status !!';
$_['error_status_exists'] 	  	  = 'Warning: Please select different order status, this one is already mapped !!';
$_['error_delete']  	  	  	  = 'Warning: Detele Status also affect Return Order and You can lost some data related to these Status !!';
$_['button_insert']    	          = 'Add New';
$_['text_approve'] = 'Assign';
$_['text_disapprove'] = 'Disapprove';
$_['text_cancel'] = 'Cancel';
$_['text_solve'] = 'Solve';
$_['text_admin'] = 'Default';
$_['tip_approve_automatic_admin'] = 'as a default status for new Return.';
$_['tip_approve_automatic_cancel'] = 'as a default cancel status for new Return.';
$_['tip_approve_automatic_solve'] = 'as a default solve status for new Return.';
$_['error_selected']              = 'Warning: Please select at least one option for deletion.';
